json.name @place.name
json.address @place.address
json.image @place.image
json.content @place.content
json.open @place.open
json.close @place.close
json.number @place.number
json.sheet @place.sheet
json.station @place.station
json.walk @place.walk
json.ptags @place.ptags